artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/AlexChicote/data_access/raw/refs/heads/main/data_in_zip/winequality-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/wineQT.csv
  STATUTS_FILE: artifacts/data_validation/status.txt
  unzip_dir: artifacts/data_ingestion

